# Change these first
owner: helionetworks # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: HelioHost
    url: $HH_UPTIME
    icon: https://raw.githubusercontent.com/HelioNetworks/status/master/assets/favicon.ico
  - name: Forums
    url: $HN_UPTIME
    icon: https://raw.githubusercontent.com/HelioNetworks/status/master/assets/favicon.ico
  - name: Tommy
    url: $TOMMY_UPTIME
    icon: https://raw.githubusercontent.com/HelioNetworks/status/master/assets/tommy.ico
  - name: Johnny
    url: $JOHNNY_UPTIME
    icon: https://raw.githubusercontent.com/HelioNetworks/status/master/assets/johnny.ico
  - name: VPS
    url: $VPS_UPTIME
    
assignees: # Users to assign downtime issues (optional)
  - Kryd0s
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.heliohost.org
  theme: dark
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/HelioNetworks/status/master/assets/logo-192.png
  name: HelioHost Status
  introTitle: "Status for HelioHost Services"
  introMessage: If you need to contact us you can post on our forum <a href="https://helionet.org/" target="_blank">helionet.org</a>, email us at <a href="mailto:support@heliohost.org" target="_blank">support@heliohost.org</a>, chat with us on <a href="https://discord.gg/fAk2rMfyba" target="_blank">Discord</a>, Tweet at us on <a href="https://twitter.com/heliohost" target="_blank">Twitter</a>, hit us in the face with a book on <a href="https://www.facebook.com/HelioHost.org/" target="_blank">Facebook</a>, text, call, or voicemail us at <a href="tel:+1-802-884-3546" target="_blank">+1 (802) 884-3546</a>, say "what's up?" to us on <a href="https://wa.me/18028843546" target="_blank">WhatsApp</a>.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
